<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>exact-math-smoke</AssemblyName>
    <RootNamespace>Dw.Tools.Math.Exact.Smoke</RootNamespace>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dw.quantities" Version="[0.2.0-preview.1]" />
    <PackageReference Include="dw.quantities.expression" Version="[0.2.0-preview.1]" />
    <PackageReference Include="dw.quantities.standard" Version="[0.2.0-preview.1]" />
  </ItemGroup>
</Project>
