<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>foundation-smoke</AssemblyName>
    <RootNamespace>Dw.Tools.Math.Foundation.Smoke</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="dw.tools.math.foundation" Version="0.1.0-preview.1" />
  </ItemGroup>
</Project>
